id = "dcm"
name = "DCM"
description = "DCM statically analyzes your Dart code to quickly find quality and consistency problems"
version = "0.1.0"
schema_version = 1
authors = ["DCM Dev <info@dcm.dev>"]
repository = "https://github.com/nelsoncampos-cloidwalk/dcm-zed-extension"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.dcm]
name = "DCM Language Server"
languages = ["Dart"]

[language_servers.dcm.initialization_options]
show_unused_code = false
show_unused_files = false
disable_baseline = false

[slash_commands.dcm]
name = "dcm"
description = "DCM analyzer commands"
tooltip_text = "Run DCM actions"
requires_argument = false
